# Generated by Django 2.2 on 2019-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
